additionalRepositories:
  - url: https://github.com/mileiq/mdlrest
    checkoutLocation: mdlrest
  - url: https://github.com/mileiq/dashboard-web-v2-app
    checkoutLocation: dashboard

tasks:
    - name: mdlrest
      before: |
          cd ../mdlrest
      init: |
          cp .env.sample .env
      image:
        file: Dockerfile
    - name: dashboard
      init: |
          echo npm install
          echo npm run build
      command: |
          echo npm run dev
